# Generated by Django 4.1.1 on 2022-11-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'BotData',
                'verbose_name_plural': 'BotDataset',
            },
        ),
    ]
