# Generated by Django 4.1.1 on 2022-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdata',
            name='category',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
